\documentclass[10pt, aspectratio=169]{beamer}

% \usetheme{ivt}
\usetheme{ivt-mono}
\usepackage{utils}
\usepackage{stuff}

\usepackage{FiraSans}
\usepackage{eulervm}
\usepackage[absolute,overlay]{textpos}

\usepackage{booktabs}
\usepackage{array}
\usepackage{graphicx}

\setbackground{white}

\SweaveOpts{engine=R, eps=FALSE, keep.source = TRUE}
<<preliminaries, echo=FALSE, results=hide>>=
options(prompt = "R> ", continue = "+  ", width = 70, useFancyQuotes = FALSE)
library("thesisSlides")
library("OPSR")
library("datapap")
library("TWTE")
@

<<model, echo=FALSE, results=hide>>=
data <- TWTE::data_model
weights <- data$weight

f <- wfh | log_weekly_km ~
  wfh_allowed + teleworkability + log_commute_km + age + dogs + driverlicense +
  fixed_workplace + hh_income + hh_size + isco_clerical + isco_managers +
  isco_agri + n_children + freq_onl_order + parking_home + parking_work +
  permanent_employed + sex_male + swiss |
  start_tracking + log_commute_km + dogs + driverlicense + fixed_workplace +
  grocery_shopper + n_children + parking_work + permanent_employed + sex_male +
  shift_work + vacation + workload |
  log_commute_km + dogs + fixed_workplace + grocery_shopper + hh_size +
  married + parking_work + sex_male + shift_work + vacation + workload +
  young_kids |
  log_commute_km + educ_higher + hh_size + married + freq_onl_order + res_loc +
  workload

fit <- opsr(f, data, weights = weights)
@

\title{Measuring and Modeling the Impact of Telework on Transport Demand -- Data, Tools and Analysis}
\author{Daniel Heimgartner}
\institute{IVT, ISTP, ETH Zürich}
\date{2025-06-05}

\begin{document}

%% Titlepage -------------------------------------------------------------------
{%
\nopagenumber
\begin{frame}
\vspace{6em}
\Large
\textbf{Measuring and Modeling the Impact of Telework on Transport Demand -- Data, Tools and Analysis}\\
\normalsize
\vspace{2em}
Daniel Heimgartner\\
\vspace{1em}
IVT, ISTP\\
ETH Zurich\\
\vspace{1em}
PhD Thesis Defense\\
Zurich, June 5th, 2025
\end{frame}
}%




%% Intro -----------------------------------------------------------------------
\begin{frame}
\huge
\vspace{1em}
Who does not know what telework is?
% I hope, no committee member raised his hand (on that note: I was told to start by thanking...)
% For the ones having raised their hand: You came badly prepared
% But thanks for coming anyways -- your love must be unconditional, because you
% clearly did not come out of interest on the topic
% Telework = home office = working from home (or if not stated explicitly -- not from the office)
\end{frame}




\begin{frame}
\huge
\vspace{1em}
Who thinks that telework leads to less travel?
% Or maybe I should ask first
\end{frame}




\begin{frame}
\huge
\vspace{1em}
Who does not speak English?
% 1 second later: everybody! perfect! For those of you that did not understand the
% question in the first place, Apéro ist um 17.00 Uhr -- das ist die wesentliche Info
% der nächsten 30 Minuten!
% first case of a selection bias: underestimating the fraction of people believing
% that telework leads to less travel...
% For those of you that did not understand the
% anyways (going to next slide)
\end{frame}




\begin{frame}
\huge
\vspace{1em}
Who thinks that telework leads to less travel?\\
\vspace{1em}
Wer denkt, dass Home Office zu weniger Verkehr führt?
% Question is also, what "less traffic/travel" really means...
\end{frame}




%% Motivation ------------------------------------------------------------------
\section{Motivation}
\sectionslide{\icon{\faHashtag} Motivation}

% Long-standing interest in the relation between telework and transport demand
% Changes brought about by the pandemic
% Telework as the lasting legacy reignited the interest
% However, evidence on the direction of effect is mixed, why?
% Second-order effects
% Modeling telework is difficult, modeling transport demand is difficult, modeling the two is also difficult...
% In this presentation (and at the core of the thesis) stands this pretty simple question: RQ: more or less travel: modeling AND measuring (model to measure).

% Overview slide
% Data + Tools + Analysis (three columns)

\begin{frame}
\frametitle{Like it or not -- our everyday lives are organized around work}
\centering
\includegraphics[width=11.5cm]{figures/full_index_plot}
\end{frame}
% If the where + when of work changes, this must have implications for transport demand.




\begin{frame}
\frametitle{Transport sector as major greenhouse gas emitter}
\begin{itemize}
\item Transport sector contributes 15\% of global greenhouse gas emissions (IPCC, 2022). % cite
\item In Switzerland, emissions are substantially higher at 31\% (BAFU, 2024). % cite
\item Reducing it through policies such as road pricing or fuel taxes is unpopular.
\item Behavioral change too...
\end{itemize}
\vspace{2em}
\icon{\faCutlery} \alert{Is telework a free lunch? However, evidence on the direction of the effect is mixed (Hook et al., 2020).} % cite}
\ivtsidebar{%
IPCC (2022). Climate Change 2022: Mitigation of Climate Change. \textit{Technical report}, Contribution of Working Group III to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.
BAFU (2024). Kenngrössen zur Entwicklung der Treibhausgasemissionen in der Schweiz 1990–2022. \textit{Technical report}, Bundesamt für Umwelt (BAFU), Bern.
Hook A, Court V, Sovacool BK, Sorrell S (2020). A Systematic Review of the Energy and Climate Impacts of Teleworking. \textit{Environmental Research Letters}, \textbf{15}(9), 093003.
}%
\end{frame}




\begin{frame}
\frametitle{Why? Second-order effects might offset foregone commutes}
\begin{itemize}
\item Time flexibility might induce leisure travel.
\item Travel chains might become less efficient.
\item Teleworkers might be willing to accept longer commutes (de Vos et al., 2018). % cite
\begin{itemize}
\item i.e., they commute less frequently but if they commute, they have to travel further.
\end{itemize}
\end{itemize}
\vspace{2em}
\icon{\faLineChart} \alert{Scholarly work over the past decade suggests that telework induces more travel (Wang and Mokhtarian, 2024).} % cite
\ivtsidebar{%
de Vos D, Meijers E, van Ham M (2018). Working From Home and the Willingness to Accept a Longer Commute. \textit{The Annals of Regional Science}, \textbf{61}(2), 375–398.
Wang X, Mokhtarian PL (2024). Examining the Treatment Effect of Teleworking on Vehicle-Miles Driven: Applying an Ordered Probit Selection Model and Incorporating the Role of Travel Stress. \textit{Transportation Research Part A}, \textbf{186}, 104072.
}%
\end{frame}




\begin{frame}
\frametitle{Main research question}
{
\large
Does telework lead to more or less travel in Switzerland?\\
}
\vspace{2em}
\icon{\faArrowsAlt} \alert{Measuring and modeling the impact of telework on transport demand.}
\end{frame}




%% Data ------------------------------------------------------------------------
\section{Data}
\sectionslide{%
\icon{\faHashtag} Data\\
\vspace{2em}
\small
Heimgartner D. and K. W. Axhausen (2024) Multimodality in the Swiss New Normal: Data Collection Methods and Response Behavior in a Multi-Stage Survey with Linked Stated Preference Designs, \emph{Transportation}, under review.
}%

% Telework landscape in Switzerland and changes brought about by the pandemic
% Weekday distribution (if we model daily basis, this needs to be accounted for,
% different network loads over the weekdays)
% Leeway (far from pandemic situation)
% Mobility tool ownership shares (SP)
% Untapped research potential (in particular, understanding decoupling can, may, want)
% I.e., differentiate between possibility, preference and choice
% => snndata (cite)

\begin{frame}
\frametitle{Switzerland's telework landscape and changes brought about by the pandemic}
\begin{itemize}
\item The pandemic has increased the telework share by 15 percentage points (pp).
\begin{itemize}
\item ...to around 40\% (who occasionally telework).
\item Oversupply during COVID (<50\% and very high share of fully remote TWers).
\end{itemize}
% However, they have normalized (especially the fully remote workers).
\item 60\% hold teleworkable jobs.
\item 91\% of them wish to utilize telework.
\item Gap of 20 pp exists between those who can work from home and those who actually do.
\item About 1/4 of teleworkers desire to telework more frequently, but barriers remain.
\end{itemize}
\ivtsidebar{%
Heimgartner D, Axhausen KW (2025). \pkg{snndata} -- Data for the Project Multimodality in the Swiss New Normal. \textit{Travel Survey Metadata Series 93}, IVT, ETH Zurich.
}%
\end{frame}



\begin{frame}
\frametitle{Untapped telework potential}
\begin{columns}
\column{0.6\textwidth}
\setkeys{Gin}{width=8cm}
\begin{figure}
\centering
<<wfh-potential, echo=FALSE, fig=TRUE, height=4, width=4.3>>=
wfh_share_simulation$p
@
\end{figure}
\column{0.4\textwidth}
\begin{itemize}
\item Mondays and Fridays are the preferred days to telework.
\item Potential leeway identified by drawing from the empirical distribution of telework frequency across weekdays, based on stated free-choice frequency.
\vspace{2em}
\item[\icon{\faCompass}] \alert{Untapped telework potential between 20 and 30 pp.}
\end{itemize}
\end{columns}
\end{frame}




%% Tools -----------------------------------------------------------------------
\section{Tools}
\sectionslide{%
\icon{\faHashtag} Tools\\
\vspace{2em}
\small
Heimgartner D. and X. Wang (2025) \pkg{OPSR}: A Package for Estimating Ordered Probit Switching Regression Models in \proglang{R}, \emph{Journal of Statistical Software}, submitted.
}%

% Shortcomings in the literature (modeling telework as an indicator)
% Boxplot telework x VMD
% Selection bias: explain intuitively (diagram and bicycle example)
% Model and formulas
% OPSR core (replication script of analysis)

\begin{frame}
\frametitle{The notorious ``What if?'' question}
\begin{itemize}
\item There is a (discrete or ordinal) event of interest.
\begin{itemize}
\item The treatment, experiment or intervention.
\end{itemize}
\item Individuals are either untreated or treated.
\item Individuals may actively choose, or passively experience the treatment (or not).
\end{itemize}
\vspace{1em}
\icon{\faFlagCheckered} \alert{Treatment effect: Estimate the effect of that event on an (individually-experienced, then aggregated) outcome of interest.}
\vspace{1em}
\begin{table}
\begin{tabular}{l|l}
\textbf{Treatment} & \textbf{Outcome}\\
Wearing a helmet while cycling & Injury severity\\
Buying a fuel-efficient car & CO$_2$ emissions or vehicle-miles driven\\
Doing a PhD at ETH Zurich & Achieving career success\\
\end{tabular}
\end{table}
\vspace{1em}
\icon{\faQuestion} \alert{With cross-sectional data, we only observe people as either treated or untreated (their factual state at the time of measurement) -- we never observe them in the opposite (counterfactual) state! ``What if?''}
\ivtsidebar{%
Mokhtarian PL (2024). The Insidious Problem of Selection Biases: How to Recognize Them, and What to Do About Them? Talk at the \textit{MIT Mobility Initiative}, \url{https://www.youtube.com/watch?v=n1cbWuShESk&t=3061s&ab_channel=MITMobilityInitiative}.
}%
\end{frame}




\begin{frame}
\frametitle{A case of a selection bias}
This would be fine, if the treatment were randomly assigned (RCT).\\
$\Rightarrow \, TE = \E[Y|\text{treated}] - \E[Y|\text{untreated}]$\\
\vspace{1em}
\icon{\faQuestion} \alert{But what if the treated group differs from the untreated group in ways that are relevant to the outcome? $\Rightarrow$ Selection bias!}
\vspace{1em}
\begin{table}
\begin{tabular}{l|l}
\textbf{Treatment} & \textbf{Self-selection}\\
Those choosing to wear a helmet & may be safer cyclists\\
Those buying a fuel-efficient car & may want to travel more\\
Those doing a PhD at ETH Zurich & may be losers in the first place\\
\end{tabular}
\end{table}
\vspace{1em}
\icon{\faFlagCheckered} \alert{Separate the treatment effect from the pre-existing differences. These pre-existing differences may be observed ($X$; ``selection on observables'') or unobserved ($\epsilon$; ``selection on unobservables'')!}
\end{frame}




\begin{frame}
\huge
\vspace{1em}
What the heck, man! So, what's the solution?
\ivtsidebar{%
Heckman J (1979). Sample Selection Bias as a Specification Error. \textit{Econometrica}, \textbf{47}(1), 153–161.
}%
\end{frame}




\begin{frame}
\frametitle{The solution: OPSR -- a form of endogenous switching regression model}
\begin{itemize}
\item Model the (ordered) treatment adoption (``selection process'') and the treatment outcome (``outcome process'') simultaneously and account for observable AND unobservable pre-existing differences.
\item[$\Rightarrow$] $TE = \E[Y|X, \text{treated}] - \E[Y|X, \text{untreated}] \alert{+ \text{correction term}}$
\item OPSR = Ordered probit model + Continuous outcome model + Error correlation
\item Similar to a latent class model where class label is observed and the two processes aren't independent.
\item[$\Rightarrow$] Probabilities of the two processes cannot simply be multiplied!
\end{itemize}
\vspace{2em}
\icon{\faWarning} \alert{$P_{\text{OPSR}} \neq \sum_{\text{treatment}=j}^{J} P(j) P(Y|j)$}
\end{frame}




\begin{frame}
\frametitle{The log-likelihood function}
\begin{multline} \label{eq:opsr-log-lik}
\ell(\theta \mid \boldsymbol{W}, \boldsymbol{X_j}) = \sum_{j = 1}^{J} \sum_{\{j\}}
\Biggl\{
  \ln\Biggl[
    \frac{1}{\sigma_j} \phi\Biggl(\frac{y_j - \Xb}{\sigma_j}\Biggr)
    \Biggr] \quad + \\
  \ln\Biggl[
    \Phi\Biggl(
      \frac{\sigma_j (\kappa_j - \Wg) - \rho_j(y_j - \Xb)}{\sigma_j\sqrt{1 - \rho_j^2}}
      \Biggr) - \\
    \Phi\Biggl(
      \frac{\sigma_j (\kappa_{j-1} - \Wg) - \rho_j(y_j - \Xb)}{\sigma_j\sqrt{1 - \rho_j^2}}
      \Biggr)
    \Biggr]
  \Biggr\}
\end{multline}
%
where...
% where ... just kidding - I am not gonna harass you with formulas
% next slide... or am I?
\end{frame}




\begin{frame}
\frametitle{The conditional expectation}
(OLS: $\E[y_j] = \Xb$)
% What is different?
\begin{equation} \label{eq:opsr-cond-exp}
\begin{aligned}
\E[y_j \mid Z = j] &= \Xb \alert{+ \E[\eta_j \mid \kappa_{j-1} - \Wg < \epsilon \le \kappa_j - \Wg]} \\
&= \Xb \alert{- \rho_j\sigma_j \frac{\phi(\kappa_j - \Wg) - \phi(\kappa_{j-1} - \Wg)}{\Phi(\kappa_j - \Wg) - \Phi(\kappa_{j-1} - \Wg)}}
\end{aligned}
\end{equation}
% where the (negative) fraction is the ordered probit switching regression model counterpart to the inverse Mills ratio (IMR) term of a binary switching regression model (because of its resemblance, we will also refer to this fraction as inverse Mills ratio in the OPSR case). We immediately see, that regressing $\boldsymbol{X_j}$ on $y_j$ leads to an omitted variable bias if $\rho_j \neq 0$ which is the root cause of the selection bias. However, the IMR can be pre-computed based on an ordered probit model and then included in the second stage regression, which describes the Heckman correction \citep{Heckman:1979}.
To obtain unbiased treatment effects, we must further evaluate the ``counterfactual outcome'', which reflects the expected outcome under a counterfactual treatment (i.e., for $j' \neq j$)
%
\begin{equation} \label{eq:opsr-counterfact-exp}
\E[\alert{y_{j'}} \mid Z = j] = \alert{\Xbd} - \alert{\rho_{j'}\sigma_{j'}} \frac{\phi(\kappa_j - \Wg) - \phi(\kappa_{j-1} - \Wg)}{\Phi(\kappa_j - \Wg) - \Phi(\kappa_{j-1} - \Wg)}
\end{equation}
If $\rho_j \neq 0$ and/or $\rho_{j'} \neq 0$ then the treatment effect is not simply $\Xb - \Xbd$ but
\begin{equation}
\E[y_j \mid Z = j] - \E[y_{j'} \mid Z = j] = \Xb - \Xbd \alert{+ \text{correction term}}
\end{equation}
\end{frame}





\begin{frame}
\frametitle{Translating math to code}
\textbf{What do we want?}
\begin{itemize}
\item Easily and flexibly specify the processes ($\Xb$ and $\Wg$).
\item Estimate the parameters.
\item Summarize the model results.
\item Easily and iteratively update the model.
\item Compare the models.
\item Compute (counterfactual) conditional expectations and thus treatment effects.
\item Summarize and visualize the treatment effects.
\item Publication grade output tables.
\end{itemize}
\vspace{2em}
\icon{\faBullhorn} \alert{We want it now and we want it to be fast!}
\end{frame}




\begin{frame}
\huge
\vspace{1em}
Enters: The \pkg{OPSR} \R-package\\
\normalsize
Available on CRAN now.\textsuperscript{*}\\
\vfill
\tiny
\textsuperscript{*}Disclaimer: The current CRAN release is outdated and has some \faBug's (among others a memory leak). The updated version has not yet been released... But is available from the \code{dev} branch here: \url{https://github.com/dheimgartner/OPSR/tree/dev}.
% Enters: (epic voice) the opsr r packge available on CRAN now.
% (very fast voice): disclaimer: the current...
% Anyways: Without OPSR this is a considerable effort, hundreds of lines of code, and error prone
% With OPSR this is a matter of hours (as I demonstrate now).
\end{frame}




%% Analysis --------------------------------------------------------------------
\section{Analysis}
\sectionslide{%
\icon{\faHashtag} Analysis\\
\vspace{2em}
\small
Heimgartner D. and K. W. Axhausen (2025) All Models are Wrong, Some Models are Wronger: On the Importance of Accounting for Self-Selection when Estimating Telework Treatment Effects, \emph{Transportation Research Part A: Policy and Practice}, to be transferred.
}%

\begin{frame}
\frametitle{What if current teleworkers were not teleworking?}
\begin{columns}[T,onlytextwidth]
\column{0.4\textwidth}
\setkeys{Gin}{width=5.5cm}
\vspace{-2em}
\begin{figure}
\centering
<<twstatus-weekly, echo=FALSE, fig=TRUE, height=4.3, width=4>>=
plot.it <- function() {
  boxplot(vmd / 1e3 ~ wfh, data = TWTE::data_analytic$weekly_indicators$vmd,
          col = "white",
          xlab = "Telework status",
          ylab = "Distance traveled (km)",
          main = "",
          notch = TRUE,
          outcol = scales::alpha("black", 0.1))
}
plot.it()
@
\end{figure}
\column{0.6\textwidth}
\begin{itemize}
\item TimeUse+ tracking data from 879 individuals (2022-07-18 -- 2023-02-09).
\item Infer telework status from time-use diary (tracked telework episodes).
\begin{itemize}
\item Non-teleworkers (NTWers; N=492)
\item Non-usual teleworkers (NUTWers; <3 days/week; N=259)
\item Usual teleworkers (UTWers; 3+ days/week; N=128)
\end{itemize}
\item Infer weekly kilometers traveled (across all modes).
\item Use the OPSR methodology to get unbiased treatment effects.
\end{itemize}
\end{columns}
\end{frame}
% We should now be aware, that the descriptive group comparison is flawed!!!




\begin{frame}[fragile]
\frametitle{\pkg{OPSR} script}
\small
<<opsr-script, eval=FALSE>>=
f <- wfh | log_weekly_km ~
  wfh_allowed + teleworkability + log_commute_km + age + dogs + driverlicense +
  fixed_workplace + hh_income + hh_size + isco_clerical + isco_managers +
  isco_agri + n_children + freq_onl_order + parking_home + parking_work +
  permanent_employed + sex_male + swiss |
  start_tracking + log_commute_km + dogs + driverlicense + fixed_workplace +
  grocery_shopper + n_children + parking_work + permanent_employed + sex_male +
  shift_work + vacation + workload |
  log_commute_km + dogs + fixed_workplace + grocery_shopper + hh_size +
  married + parking_work + sex_male + shift_work + vacation + workload +
  young_kids |
  log_commute_km + educ_higher + hh_size + married + freq_onl_order + res_loc +
  workload

fit <- opsr(f, data, weights = weights)
summary(fit)

opsr_te(fit, type = "unlog-response")
plot(fit, type = "unlog-response")
@
\end{frame}

% The replication code of the analysis fits on one slide and estimation and
% post-estimation is super easy -- even my grandfather could do it!




\begin{frame}[fragile]
\frametitle{\code{R> summary(fit)}}
\small
<<opsr-summary, eval=FALSE>>=
print(summary(fit), print.call = FALSE)
@
\begin{Soutput}
BFGS maximization, 344 iterations
Return code 0: successful convergence
Runtime: 3.26 secs
Number of regimes: 3
Number of observations: 879 (492, 259, 128)
Estimated parameters: 71

Log-Likelihood: -1015.052
AIC: 2172.104
BIC: 2511.398
Pseudo R-squared (EL): 0.3053
Pseudo R-squared (MS): 0.2095
Multiple R-squared: 0.6136 (0.6419, 0.6553, 0.3222)
...
\end{Soutput}
\end{frame}




\begin{frame}[fragile]
\frametitle{Wald test suggests that there is error correlation}
\small
\begin{Soutput}
Estimates:
                        Estimate Std. error t value  Pr(> t)
kappa1                  2.386065   0.755027   3.160 0.001576 **
kappa2                  3.601433   0.754574   4.773 1.82e-06 ***
s_teleworkability       0.253970   0.035869   7.080 1.44e-12 ***
...
o1_(Intercept)          2.888933   0.306988   9.411  < 2e-16 ***
...
sigma1                  0.393013   0.020533  19.141  < 2e-16 ***
sigma2                  0.411519   0.038681  10.639  < 2e-16 ***
sigma3                  0.462633   0.063710   7.262 3.83e-13 ***
rho1                    0.186624   0.422601   0.442 0.658774
rho2                    0.502810   0.096370   5.217 1.81e-07 ***
rho3                    0.198015   0.396531   0.499 0.617520
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Wald chi2 (null): 1647.465 on 60 DF, p-value: < 0
Wald chi2 (rho): 27.4168 on 3 DF, p-value: < 0
\end{Soutput}
\end{frame}




\begin{frame}
\Large
\vspace{1em}
\begin{equation*}
\E[y_j \mid Z = j] = \Xb - \alert{\rho_j}\sigma_j \frac{\phi(\kappa_j - \Wg) - \phi(\kappa_{j-1} - \Wg)}{\Phi(\kappa_j - \Wg) - \Phi(\kappa_{j-1} - \Wg)}
\end{equation*}
\ivtsidebar{%
\url{https://github.com/dheimgartner/thesisSlides/blob/main/vignettes/figures/heckman-would-be-proud.gif}
}%
\end{frame}




\begin{frame}[fragile]
\frametitle{\code{R> opsr\_te(fit, type = "unlog-response")}}
<<opsr-te, echo=FALSE>>=
opsr_te(fit, type = "unlog-response")
@
\end{frame}




\begin{frame}
\frametitle{\code{R> plot(fit, type = "unlog-response")}}
\setkeys{Gin}{width=0.65\textwidth}
\vspace{-0.5em}
\begin{figure}
\centering
<<opsr-plot, echo=FALSE, fig=TRUE, height=7, width=8>>=
plot(fit, type = "unlog-response",
  labels.diag = c("NTWing", "NUTWing", "UTWing"),
  labels.reg = c("NTWers", "NUTWers", "UTWers"),
  xlim = c(0, 800), ylim = c(0, 800), cex = 1.5)
@
\end{figure}
\end{frame}



\begin{frame}
\frametitle{Telework treatment effects}
\begin{columns}[T,onlytextwidth]
\column{0.6\textwidth}
\setkeys{Gin}{width=\textwidth}
\vspace{-2em}
\begin{figure}
\centering
<<te, echo=FALSE, fig=TRUE, height=5, width=6>>=
x <- te_plot$x
xlabs <- te_plot$xlabs
mat <- te_plot$mat

plot.it <- function() {
  matplot(x = x, mat, type = "b", xlab = "Telework treatment", ylab = "Weekly distance (km)",
          axes = FALSE, pch = 19, lty = 1, lwd = 2.5, ylim = c(0, 350))
  axis(1, at = x, labels = xlabs, padj = 0.5)
  axis(2)
  grid()
  legend("topright", legend = c("NTWers", "NUTWers", "UTWers"), pch = 19, col = 1:3, lwd = 2.5, bty = "n")
  box()
}

plot.it()
@
\end{figure}
\column{0.4\textwidth}
\begin{itemize}
\small
\item Counterfactual weekly km traveled are very different.
\item Telework reduces travel of a particularly mobile group (with longer commutes).
\item Unit treatment effects indicate that travel reduction roughly corresponds to 2-way commute distance.
\item Travel reduction amounts to 16\% (aligns with Sallard, 2024).
\item Descriptive analysis shows, that time allocation is very similar across the TWer groups -- except for travel.
\end{itemize}
\end{columns}
\vspace{1em}
\icon{\faWarning} \alert{Not accounting for error correlation underestimates treatment effects.}
\ivtsidebar{%
Sallard A (2024). \textit{Mobility, Population, and Social Spaces: Understanding Travel Demand in a Changing World}. Ph.D. thesis, ETH Zürich, Zürich
}%
\end{frame}
% Remeber the boxplot from before? This was essentially comparing these three points.




%% Outro -----------------------------------------------------------------------
\section{Conclusion}
\sectionslide{\icon{\faHashtag} Conclusion}
% See NOTES.md (starting line 28)
% Including limitations

\begin{frame}
\frametitle{Takeaways}
\begin{itemize}
\item Telework changes travel by cutting commutes and shifting trips from the central business district (CBD) to home.
\begin{itemize}
\item Result: 16\% less travel and more dispersed trip timing and locations.
\item Mobility tool ownership and mode shares stay stable.
\end{itemize}
\item Switzerland still has 20 pp untapped telework potential on any weekday.
\item Mixed effects reported in the literature may stem from selection bias when using cross-sectional data.
\item The \pkg{OPSR} package makes replicating this analysis simple.
\item It also opens doors for broader applications beyond transportation.
\end{itemize}
\vspace{1em}
\icon{\faLegal} \alert{Selection bias is widespread and can mislead policy -- addressing it is crucial.}
\end{frame}

\sectionslide{\icon{\faHashtag} Thank you!}
% With that, let's recall the collective wisdom of the audience, where XXX % said, that telework leads to less travel
% What took you 5 seconds to answer, took me 3.5 years...
% END




\sectionslide{\icon{\faHashtag} Appendix}

\begin{frame}
\frametitle{Limitations}
\begin{itemize}
\item The case of Switzerland (but: \pkg{OPSR} to easily replicate the analysis, e.g., based on national census).
\item Multivariate normal only one possible error distribution.
\begin{itemize}
\item Distributional assumptions should be checked (but how? $\epsilon$ is latent).
\item Copula modeling (but no unified framework -- at least not in \R).
\end{itemize}
\item Backward selection (starting from an overfitted model) and identification issues.
\item Why not leveraging the panel structure?
\begin{itemize}
\item Telework is used very opportunistically and flexibly (varies over the weeks).
\item Unobserved factors that influence this (short-term) decision and VMD.
\item[$\Rightarrow$] Greetings from Heckman!
\end{itemize}
\item Commute distance as explanatory variable?
\item Arbitrary classification of teleworker groups (NTWers, NUTWers, UTWers).
\item Incomplete understanding of employer-side (simplified modeling of telework adotion).
\item LOL value proposition: Reinventing the wheel (\pkg{OPSR}).
\end{itemize}
\end{frame}




\begin{frame}
\frametitle{Long-standing interest in the relation between telework and transport demand}
\begin{itemize}
\item Telework shares quadrupled during the pandemic (Barrero et al., 2023). % cite
\item First paper: Mobility changes brought about by the pandemic.
\begin{itemize}
\item Adjustments to the extraordinary circumstances were not made habitual (e.g., not a change in underlying preferences, but ``applying'' these preferences in a new environment).
\end{itemize}
\item Telework as the lasting legacy of the pandemic reignited the interest.
\end{itemize}
\vspace{2em}
\icon{\faBalanceScale} \alert{However: Evidence on the direction of the effect is mixed (Hook et al., 2020).} % cite
\ivtsidebar{%
Barrero JM, Bloom N, Davis SJ (2023). The Evolution of Work From Home. \textit{Journal of Economic Perspectives}, \textbf{37}(4), 23–50.
Hook A, Court V, Sovacool BK, Sorrell S (2020). A Systematic Review of the Energy and Climate Impacts of Teleworking. \textit{Environmental Research Letters}, \textbf{15}(9), 093003.
}%
\end{frame}




\begin{frame}
\frametitle{Data, \greyout{tools and analysis}}
\begin{columns}[T,onlytextwidth]
\column{0.4\textwidth}
\textbf{Data}
\begin{itemize}
\small
\item Three stage survey instrument (fielded after the pandemic).
\item Understand the (evolution of the) telework landscape in Switzerland.
\item Two stated preference experiments.
\begin{itemize}
\item Leverage of employer-side incentives (hybrid work arrangements).
\item Impact of telework on mobility tool ownership (previously neglected second-order effect).
\end{itemize}
\end{itemize}

\column{0.3\textwidth}
\vspace{4em}
\greyout{\textbf{Tools}}
\begin{greyitemize}
\small
\item Suitable modeling framework.
\item Implementation thereof in \R.
\end{greyitemize}

\column{0.3\textwidth}
\vspace{8em}
\greyout{\textbf{Analysis}}
\begin{greyitemize}
\small
\item Applying the tools to
\item TimeUse+ data (time-use and travel diary data using a smartphone tracking app).
\end{greyitemize}

\end{columns}
\vspace{1em}
\icon{\faFlask} \alert{Rich data source to investigate telework in Switzerland.}
\ivtsidebar{%
\url{https://www.research-collection.ethz.ch/handle/20.500.11850/737879}
}%
\end{frame}
% Untapped research potential -- link!



\begin{frame}
\frametitle{\greyout{Data,} tools \greyout{and analysis}}
\begin{columns}[T,onlytextwidth]
\column{0.4\textwidth}
\greyout{\textbf{Data}}
\begin{greyitemize}
\small
\item Three stage survey instrument (fielded after the pandemic).
\item Understand the (evolution of the) telework landscape in Switzerland.
\item Two stated preference experiments.
\begin{itemize}
\item Leverage of employer-side incentives (hybrid work arrangements).
\item Impact of telework on mobility tool ownership (previously neglected second-order effect).
\end{itemize}
\end{greyitemize}

\column{0.3\textwidth}
\vspace{4em}
\textbf{Tools}
\begin{itemize}
\small
\item Suitable modeling framework.
\item Implementation thereof in \R.
\end{itemize}

\column{0.3\textwidth}
\vspace{8em}
\greyout{\textbf{Analysis}}
\begin{greyitemize}
\small
\item Applying the tools to
\item TimeUse+ data (time-use and travel diary data using a smartphone tracking app).
\end{greyitemize}

\end{columns}
\vspace{1em}
\icon{\faFlask} \alert{\pkg{OPSR} statistical software.}
\ivtsidebar{%
\url{https://cran.r-project.org/package=OPSR}
}%
\end{frame}




\begin{frame}
\frametitle{\greyout{Data, tools and} analysis}
\begin{columns}[T,onlytextwidth]
\column{0.4\textwidth}
\greyout{\textbf{Data}}
\begin{greyitemize}
\small
\item Three stage survey instrument (fielded after the pandemic).
\item Understand the (evolution of the) telework landscape in Switzerland.
\item Two stated preference experiments.
\begin{itemize}
\item Leverage of employer-side incentives (hybrid work arrangements).
\item Impact of telework on mobility tool ownership (previously neglected second-order effect).
\end{itemize}
\end{greyitemize}

\column{0.3\textwidth}
\vspace{4em}
\greyout{\textbf{Tools}}
\begin{greyitemize}
\small
\item Suitable modeling framework.
\item Implementation thereof in \R.
\end{greyitemize}

\column{0.3\textwidth}
\vspace{8em}
\textbf{Analysis}
\begin{itemize}
\small
\item Applying the tools to
\item TimeUse+ data (time-use and travel diary data using a smartphone tracking app; Winkler et al., 2024). % cite
\end{itemize}

\end{columns}
\vspace{1em}
\icon{\faFlask} \alert{Estimating telework treatment effects leveraging RP data and being mindful of selection bias.}
\ivtsidebar{%
Winkler C, Meister A, Axhausen KW (2024). The TimeUse+ Data Set: 4 Weeks of Time Use and Expenditure Data Based on GPS Tracks. \textit{Transportation}, pp. 1–27.
}%
\end{frame}



\begin{frame}
\frametitle{Wrong (group comparison)}
% The illusion of comparing groups
% Modeling it as an indicator
% Selection on observables and unobservables
\includegraphics[width=0.92\textwidth]{figures/te-illustration-1}
\end{frame}



\begin{frame}
\frametitle{Still wrong (controlling for observables)}
% The illusion of comparing groups
% Modeling it as an indicator
% Selection on observables and unobservables
\includegraphics[width=0.92\textwidth]{figures/te-illustration-2}
\end{frame}




\begin{frame}
\frametitle{Right but not observable (longitudinal estimate)}
% The illusion of comparing groups
% Modeling it as an indicator
% Selection on observables and unobservables
\includegraphics[width=\textwidth]{figures/te-illustration-3}
\ivtsidebar{%
Figure based on: Wang X, Mokhtarian PL (2024). Examining the Treatment Effect of Teleworking on Vehicle-Miles Driven: Applying an Ordered Probit Selection Model and Incorporating the Role of Travel Stress. \textit{Transportation Research Part A}, \textbf{186}, 104072.
}%
\end{frame}




\begin{frame}
\frametitle{Implications for mobility tool ownership}
\setkeys{Gin}{width=\textwidth}
\begin{figure}
\centering
<<mto, echo=FALSE, fig=TRUE, height=7, width=9>>=
plot.it <- function() {
  op <- par(no.readonly = TRUE)
  on.exit(par(op))
  dat <- bootstrap$mat.bs
  par(mfrow = c(3, 4))

  plt <- function(x, main, col, col.zero) {
    mean_line <- apply(x, 2, mean)
    lower <- apply(x, 2, function(x) quantile(x, probs = 0.025))
    upper <- apply(x, 2, function(x) quantile(x, probs = 0.975))
    ml0 <- mean_line[1]
    mean_line <- mean_line - ml0
    lower <- lower - ml0
    upper <- upper - ml0
    mat <- t(x)
    mat <- mat - ml0
    matplot(x = 0:5, mat, type = "l", lty = 1, col = scales::alpha(col, alpha = 0.075),
            xlab = "Telework frequency (d/week)",
            ylab = "Ownership share (normalized)",
            main = main)
    lp <- ifelse(main == "Half-fare", "topleft", "bottomleft")
    legend(lp, legend = c("mean", "2.5th perc.", "97.5th perc."),
           lty = c(1, 3, 3), col = col, bty = "n")
    grid()
    lines(x = 0:5, y = mean_line, col = col, lwd = 2)
    lines(x = 0:5, y = lower, col = col, lwd = 1, lty = 3)
    lines(x = 0:5, y = upper, col = col, lwd = 1, lty = 3)
    abline(h = 0, col = col.zero)
  }

  main <- c("Regular bike", "Car", "Car sharing", "E-bike", "National ST", "Half-fare", "Regional ST")
  for (i in seq_along(dat)) {
    plt(dat[[i]], main[i], datapap::my_colors$colvec[3], "darkgrey")
  }
}

plot.it()
@
\end{figure}
\begin{textblock*}{4cm}(11.5cm,6cm)  % width, (x,y)
\small\alert{3 d/week seems to be the tipping point!}
\end{textblock*}
\end{frame}




\begin{frame}
\frametitle{OPSR vs. indicator variable approach}
\begin{columns}[T,onlytextwidth]
\column{0.5\textwidth}
\textbf{Indicator approach (assuming no interactions)}
\begin{itemize}
\item Weekly km traveled is a function of $X$ ($Y(X)$).
\item Telework is exogenous -- i.e., there are no factors simultaneously influencing telework and the error term\\$\Rightarrow$ Level effects.
\end{itemize}
\alert{Treatment effect is simply the level effect of the telework indicator. However, (all!) parameter estimates might be biased!}
\column{0.5\textwidth}
\textbf{OPSR}
\begin{itemize}
\item Weekly km traveled is a function of $X$ but the effect of $x$ depends on telework status $J$ ($Y(X|J)$).
\begin{itemize}
\item For example: The effect of having children on weekly km traveled might be different for NTWers (bring children to school as part of the commute) and UTWers (extra trip).
\end{itemize}
\item Telework is endogenous -- i.e., there are (unobserved) factors simultaneously influencing telework adoption and weekly km traveled.
\end{itemize}
\alert{Treatment effect is a result of 1. different parameters/process specifications for the groups (i.e., the $X_j\beta_j)$ and $X_{j'}\beta_{j'}$ and 2. the selection on unobservables (IMR term; see Equations~\ref{eq:opsr-cond-exp} and \ref{eq:opsr-counterfact-exp}).}
\end{columns}
\end{frame}




\begin{frame}[fragile]
\frametitle{Telework treatment effects}
\begin{table}
\centering
<<te-table, echo=FALSE, results=tex>>=
tab <- TWTE::model_km$table_ate
tab <- gsub("\\\\toprule", "", tab)
cat(tab)
@
\label{tab:te}
\end{table}
\end{frame}




\begin{frame}[fragile]
\frametitle{Telework unit treatment effects}
\begin{table}
\centering
<<ute-table, echo=FALSE, results=tex>>=
tab <- TWTE::model_km$table_ute
cat(tab)
@
\end{table}
Unit treatment effects (UTE) are computed by dividing the TE (from Page~\ref{tab:te}) by the difference in telework frequency.
\end{frame}

\begin{frame}
\frametitle{Not accounting for error correlation underestimates the treatment effects}
\begin{table}
\centering
\begin{tabular}{llrrrr}
& & \multicolumn{3}{c}{Telework status} \\
\cmidrule{3-5}
& \multicolumn{1}{c}{Treatment} & NTWers & NUTWers & UTWers & ATE \\
\midrule
OPSR & NTWing$\rightarrow$NUTWing &  -69.911 &  -54.006 &  -29.523 &  -59.576\\
 & NTWing$\rightarrow$UTWing & -110.981 & -109.338 & -139.912 & -115.009\\
 & NUTWing$\rightarrow$UTWing &  -41.070 &  -55.332 & -110.390 &  -55.433\\ \addlinespace
Rho = 0 & NTWing$\rightarrow$NUTWing &  -38.245 &  -40.882 &  -47.310 &  -40.323\\
 & NTWing$\rightarrow$UTWing &  -94.319 &  -85.610 & -107.308 &  -94.063\\
 & NUTWing$\rightarrow$UTWing &  -56.074 &  -44.728 &  -59.998 &  -53.740\\ \addlinespace
$\Delta$ & NTWing$\rightarrow$NUTWing &  -31.666 &  -13.124 &   17.787 &  -19.253\\
 & NTWing$\rightarrow$UTWing &  -16.662 &  -23.728 &  -32.605 &  -20.946\\
 & NUTWing$\rightarrow$UTWing &   15.004 &  -10.605 &  -50.392 &   -1.692\\ \addlinespace
\% & NTWing$\rightarrow$NUTWing &  -45.295 &  -24.300 &   60.249 &  -32.317\\
 & NTWing$\rightarrow$UTWing &  -15.013 &  -21.702 &  -23.304 &  -18.212\\
 & NUTWing$\rightarrow$UTWing &   36.534 &  -19.166 &  -45.649 &   -3.053\\\bottomrule
\end{tabular}
\end{table}
\end{frame}

\end{document}
